//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanGiay
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTSP_KM
    {
        public int MaCTSP { get; set; }
        public int MaKhuyenMai { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual KhuyenMai KhuyenMai { get; set; }
    }
}
