//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanGiay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher1
    {
        public int MaVoucher { get; set; }
        public string MaCode { get; set; }
        public decimal SoTienGiam { get; set; }
        public decimal DieuKienGiam { get; set; }
        public int TrangThai { get; set; }
    }
}
